spring:
  datasource:
    url: jdbc:mysql://localhost/vollmed_api
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${JWT_SECRET:123456789}

## Usado para ver os parâmetros nas consultas SQL
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace



