spring:
  datasource:
    url: jdbc:mysql://localhost/vollmed_api
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

## Usado para ver os parâmetros nas consultas SQL
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace



